name: NPM Publish

on: push

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JS-DevTools/npm-publish@v1
        with:
          access: public